name: Angular Build

on:
  push:
    branches: [ "main", "feature/*", "bugfix/*" ]

  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/feature-tracker-angular
    steps:
      - uses: actions/checkout@v5

      # Setup QEMU (for arm emulation on amd64 runner)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Setup Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build with npm
        run: npm run build

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build amd64 image
      - name: Build amd64 image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker buildx build -t $DOCKER_IMAGE_NAME-amd64 --platform linux/amd64 --push .

      # Build arm64 image
      - name: Build arm64 image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker buildx build -t $DOCKER_IMAGE_NAME-arm64 --platform linux/arm64 --push .

      # Merge them into multi-arch manifest
      - name: Create multi-arch manifest
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker buildx imagetools create \
            -t docker.io/$DOCKER_IMAGE_NAME:latest \
            docker.io/$DOCKER_IMAGE_NAME-amd64 \
            docker.io/$DOCKER_IMAGE_NAME-arm64
